# Generated by Django 6.0.6 on 2026-06-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stickynote",
            name="color",
            field=models.CharField(default="#FEF3C7", max_length=7),
        ),
        migrations.AlterField(
            model_name="stickynote",
            name="content",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="stickynote",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="stickynote",
            name="title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="stickynote",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
